# Deploy the main.bicep file to azure

name: Deploy Azure Resources

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install Bicep CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Create resource group
      run: |
        az group create \
          --name ${{ env.AZURE_RESOURCE_GROUP_NAME }} \
          --location ${{ env.AZURE_LOCATION }}

    - name: Deploy Bicep file
      run: |
        bicep build main.bicep
        az deployment sub create \
          --name ${{ env.AZURE_RESOURCE_GROUP_NAME }} \
          --location ${{ env.AZURE_LOCATION }} \
          --template-file main.json